### ISSUE TITLE
Question: How to properly use Daz textures in Godot?

### ISSUE THREAD

**Issue by ghost** [smix8/Godot_DAZ_Studio_Guide#1]
Hello Smix, 

Do you know how to appropriately use Daz textures within Godot? I've tried this before with Unity, and things usually look jpeg-y and flat. Now that I'm moving to Godot, I'd like to seek advice, assuming you've dealt with this before.

And thank you for sharing all of this information!

**Comment by smix8** [comment]
The normal and bump map textures in DAZ are usually of very poor quality which is hidden below the raytraced renderer on a 3D model with a 1-3x subdivision.

The newer versions of the Blender DAZ importer have an option to bake new normal maps for the imported model and this is the way to go. Import the highres model, add another 1-3x subdivisions for even more model detail and bake new, highquality normal maps for the models that you later use in Godot on the lowres 3D model.

You also need to make a custom shader in Godot to emulate most of the DAZ shader properties for a similar look as far as realtime render can compared to raytraced renderer. The default spatial shader will not work at all and look ugly no matter what you do. Especially for hair the default shader is a lost cause.

Usually you also need to fix / increase the UV map margins for the body textures. A typical DAZ model consists of multiple surfaces and shaders and you will see lack/grey/white color seems at a distance due to the mipmaps of a realtime render like Godot.

**Comment by ghost** [comment]
Thanks for this insight, I will be trying some experiments over the next few weeks with Godot.
